on:
  schedule:
  - cron:  "*/7 * * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/karolkrawczyk/karol_test_repo.git"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
